import React, { useState, useRef, useEffect } from "react";
import { Copy, RotateCcw, X, Sliders, Check, GripHorizontal } from "lucide-react";

export function HandSlotCalibrator({
  gender,
  slots,
  onUpdateSlot,
  onResetSlots,
  onClose,
}) {
  const [activeFinger, setActiveFinger] = useState(0);
  const [copied, setCopied] = useState(false);
  const [position, setPosition] = useState({ x: 0, y: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const dragRef = useRef({ startX: 0, startY: 0, posX: 0, posY: 0 });

  const handleMouseDown = (e) => {
    if (e.target.closest("button") || e.target.closest("input")) return;
    setIsDragging(true);
    dragRef.current = {
      startX: e.clientX,
      startY: e.clientY,
      posX: position.x,
      posY: position.y,
    };
  };

  useEffect(() => {
    if (!isDragging) return;

    const handleMouseMove = (e) => {
      const dx = e.clientX - dragRef.current.startX;
      const dy = e.clientY - dragRef.current.startY;
      setPosition({
        x: dragRef.current.posX + dx,
        y: dragRef.current.posY + dy,
      });
    };

    const handleMouseUp = () => {
      setIsDragging(false);
    };

    document.addEventListener("mousemove", handleMouseMove);
    document.addEventListener("mouseup", handleMouseUp);
    return () => {
      document.removeEventListener("mousemove", handleMouseMove);
      document.removeEventListener("mouseup", handleMouseUp);
    };
  }, [isDragging]);

  const fingerLabels = ["Thumb", "Index", "Middle", "Ring", "Pinky"];
  const currentSlot = slots[activeFinger] || slots[0];

  // Helper to parse numeric values from string (e.g. "22%" -> 22, "-24deg" -> -24)
  const parseNum = (val, defaultVal = 0) => {
    if (typeof val === "number") return val;
    if (!val) return defaultVal;
    const num = parseFloat(String(val).replace(/[^0-9.-]/g, ""));
    return isNaN(num) ? defaultVal : num;
  };

  const currentLeft = parseNum(currentSlot.left, 20);
  const currentTop = parseNum(currentSlot.top, 20);
  const currentWidth = parseNum(currentSlot.width, 10);
  const currentRotate = parseNum(currentSlot.rotate, 0);

  const handleChange = (field, value) => {
    let formattedVal = value;
    if (field === "left" || field === "top" || field === "width") {
      formattedVal = `${value}%`;
    } else if (field === "rotate") {
      formattedVal = `${value}deg`;
    }
    onUpdateSlot(activeFinger, field, formattedVal);
  };

  const handleCopyCode = () => {
    const formattedConfig = `/**
 * HAND SLOT CONFIGURATION FILE
 * Auto-generated by Live Calibration UI
 */

export const HAND_SLOT_CONFIG = {
  woman: ${JSON.stringify(
    slots.map((s) => ({
      label: s.label,
      index: s.index,
      left: s.left,
      top: s.top,
      width: s.width,
      height: s.height || "auto",
      rotate: s.rotate,
    })),
    null,
    4,
  )},
  man: ${JSON.stringify(
    slots.map((s) => ({
      label: s.label,
      index: s.index,
      left: s.left,
      top: s.top,
      width: s.width,
      height: s.height || "auto",
      rotate: s.rotate,
    })),
    null,
    4,
  )}
};

export function getHandSlots(gender = "woman") {
  const slots = HAND_SLOT_CONFIG[gender] || HAND_SLOT_CONFIG.woman;
  return slots.map((slot) => ({
    ...slot,
    style: {
      left: slot.left,
      top: slot.top,
      width: slot.width,
      height: slot.height || "auto",
      transform: \`rotate(\${slot.rotate})\`,
    },
  }));
}
`;

    navigator.clipboard.writeText(formattedConfig);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div
      className={`hand-calibrator-panel ${isDragging ? "dragging" : ""}`}
      style={{
        transform: `translate(${position.x}px, ${position.y}px)`,
      }}
    >
      <div
        className="calibrator-header"
        onMouseDown={handleMouseDown}
        style={{ cursor: isDragging ? "grabbing" : "grab" }}
        title="Giữ chuột và kéo để di chuyển bảng"
      >
        <div className="calibrator-title">
          <GripHorizontal size={16} className="grip-icon" />
          <span>Calibrate Nails ({gender.toUpperCase()})</span>
        </div>
        <button
          type="button"
          className="calibrator-close-btn"
          onClick={onClose}
          title="Close calibrator"
        >
          <X size={16} />
        </button>
      </div>

      {/* Finger selector chips */}
      <div className="calibrator-finger-tabs">
        {fingerLabels.map((label, idx) => (
          <button
            key={label}
            type="button"
            className={`calibrator-chip ${activeFinger === idx ? "active" : ""}`}
            onClick={() => setActiveFinger(idx)}
          >
            {label}
          </button>
        ))}
      </div>

      {/* Sliders and direct number inputs for active finger */}
      <div className="calibrator-controls">
        <div className="calibrator-control-group">
          <label>
            <span>Left (X Position)</span>
            <input
              type="number"
              className="calibrator-num-input"
              step="0.1"
              value={currentLeft}
              onChange={(e) =>
                handleChange("left", parseFloat(e.target.value) || 0)
              }
            />
          </label>
          <input
            type="range"
            min="-20"
            max="110"
            step="0.1"
            value={currentLeft}
            onChange={(e) => handleChange("left", parseFloat(e.target.value))}
          />
        </div>

        <div className="calibrator-control-group">
          <label>
            <span>Top (Y Position)</span>
            <input
              type="number"
              className="calibrator-num-input"
              step="0.1"
              value={currentTop}
              onChange={(e) =>
                handleChange("top", parseFloat(e.target.value) || 0)
              }
            />
          </label>
          <input
            type="range"
            min="-20"
            max="105"
            step="0.1"
            value={currentTop}
            onChange={(e) => handleChange("top", parseFloat(e.target.value))}
          />
        </div>

        <div className="calibrator-control-group">
          <label>
            <span>Width (Size)</span>
            <input
              type="number"
              className="calibrator-num-input"
              step="0.1"
              value={currentWidth}
              onChange={(e) =>
                handleChange("width", parseFloat(e.target.value) || 0)
              }
            />
          </label>
          <input
            type="range"
            min="2"
            max="40"
            step="0.1"
            value={currentWidth}
            onChange={(e) => handleChange("width", parseFloat(e.target.value))}
          />
        </div>

        <div className="calibrator-control-group">
          <label>
            <span>Rotation (Angle)</span>
            <input
              type="number"
              className="calibrator-num-input"
              step="1"
              value={currentRotate}
              onChange={(e) =>
                handleChange("rotate", parseFloat(e.target.value) || 0)
              }
            />
          </label>
          <input
            type="range"
            min="-180"
            max="180"
            step="1"
            value={currentRotate}
            onChange={(e) =>
              handleChange("rotate", parseFloat(e.target.value))
            }
          />
        </div>
      </div>

      {/* Action buttons */}
      <div className="calibrator-actions">
        <button
          type="button"
          className="calibrator-btn copy-btn"
          onClick={handleCopyCode}
        >
          {copied ? <Check size={15} /> : <Copy size={15} />}
          <span>{copied ? "Copied JS Code!" : "Copy JS Code"}</span>
        </button>

        <button
          type="button"
          className="calibrator-btn reset-btn"
          onClick={onResetSlots}
          title="Reset to default config"
        >
          <RotateCcw size={15} />
          <span>Reset</span>
        </button>
      </div>
    </div>
  );
}
