/**
 * HAND SLOT CONFIGURATION FILE
 * Auto-generated by Live Calibration UI
 */

export const HAND_SLOT_CONFIG = {
  woman: [
    {
      label: "Thumb",
      index: 0,
      left: "-2%",
      top: "28.8%",
      width: "26.2%",
      height: "auto",
      rotate: "-55deg",
    },
    {
      label: "Index",
      index: 1,
      left: "9.6%",
      top: "-2.3%",
      width: "32.7%",
      height: "auto",
      rotate: "-20deg",
    },
    {
      label: "Middle",
      index: 2,
      left: "27.5%",
      top: "-12.7%",
      width: "38.8%",
      height: "auto",
      rotate: "0deg",
    },
    {
      label: "Ring",
      index: 3,
      left: "45.5%",
      top: "-6.9%",
      width: "37.6%",
      height: "auto",
      rotate: "7deg",
    },
    {
      label: "Pinky",
      index: 4,
      left: "62.3%",
      top: "10.7%",
      width: "27.1%",
      height: "auto",
      rotate: "9deg",
    },
  ],
  man: [
    {
      label: "Thumb",
      index: 0,
      left: "-2%",
      top: "28.8%",
      width: "26.2%",
      height: "auto",
      rotate: "-55deg",
    },
    {
      label: "Index",
      index: 1,
      left: "9.6%",
      top: "-2.3%",
      width: "32.7%",
      height: "auto",
      rotate: "-20deg",
    },
    {
      label: "Middle",
      index: 2,
      left: "27.5%",
      top: "-12.7%",
      width: "38.8%",
      height: "auto",
      rotate: "0deg",
    },
    {
      label: "Ring",
      index: 3,
      left: "45.5%",
      top: "-6.9%",
      width: "37.6%",
      height: "auto",
      rotate: "7deg",
    },
    {
      label: "Pinky",
      index: 4,
      left: "62.3%",
      top: "10.7%",
      width: "27.1%",
      height: "auto",
      rotate: "9deg",
    },
  ],
};

export function getHandSlots(gender = "woman") {
  const slots = HAND_SLOT_CONFIG[gender] || HAND_SLOT_CONFIG.woman;
  return slots.map((slot) => ({
    ...slot,
    style: {
      left: slot.left,
      top: slot.top,
      width: slot.width,
      height: slot.height || "auto",
      transform: `rotate(${slot.rotate})`,
    },
  }));
}
