export const NAIL_DESIGN_SUMMARY = [
  {
    label: "Total designs",
    value: "8",
    description: "mock catalog entries available for admin review",
  },
  {
    label: "Featured",
    value: "3",
    description: "designs currently highlighted on promotional surfaces",
  },
  {
    label: "Draft concepts",
    value: "2",
    description: "designs still waiting for final merchandising approval",
  },
];

const createMockNailDesign = (
  id,
  name,
  category,
  collection,
  status,
  price,
  duration,
  artist,
  popularity,
  updatedAt,
  palette,
  tags,
  description,
  notes,
) => ({
  id,
  name,
  category,
  collection,
  status,
  price,
  duration,
  artist,
  popularity,
  updatedAt,
  palette,
  tags,
  description,
  notes,
});

const NAIL_DESIGN_ROW_DEFINITIONS = [
  [
    "ND-3001",
    "Rose Chrome Bloom",
    "Chrome",
    "Summer 2026",
    "Published",
    "420,000 VND",
    "90 min",
    "Ariana Vo",
    "Trending",
    "2026-05-30",
    "Rose gold, pearl white, mirror silver",
    "chrome, floral, bridal",
    "High-shine chrome base with sculpted rose petals and pearl accents.",
    "Pinned for homepage campaign and premium upsell bundle.",
  ],
  [
    "ND-3002",
    "Matcha Minimal Tips",
    "Minimal",
    "Everyday Edit",
    "Published",
    "260,000 VND",
    "55 min",
    "Bao Tran",
    "Stable",
    "2026-05-28",
    "Matcha green, nude beige, milky white",
    "minimal, short nails, office",
    "Clean diagonal French tips with soft green accents for daily wear.",
    "Performs well with office-worker audience in District 1.",
  ],
  [
    "ND-3003",
    "Sunset Aura Glaze",
    "Aura",
    "Summer 2026",
    "Draft",
    "390,000 VND",
    "75 min",
    "Linh Pham",
    "Rising",
    "2026-06-01",
    "Apricot, coral pink, soft amber",
    "aura, gradient, glossy",
    "Soft airbrushed aura blend with syrup gloss finish.",
    "Needs final photo retouch and naming approval before publishing.",
  ],
  [
    "ND-3004",
    "Velvet Midnight Cat Eye",
    "Cat Eye",
    "Night Luxe",
    "Published",
    "450,000 VND",
    "95 min",
    "Hanh Vo",
    "Trending",
    "2026-05-24",
    "Midnight blue, graphite, silver flare",
    "cat eye, magnetic, glam",
    "Magnetic cat-eye reflection with deep navy base and foil sparkle.",
    "Strong repeat-booking rate from evening event customers.",
  ],
  [
    "ND-3005",
    "Peach Jelly Crystals",
    "Jelly",
    "Glass Candy",
    "Archived",
    "340,000 VND",
    "70 min",
    "Thao Bui",
    "Cooling",
    "2026-04-19",
    "Peach jelly, clear gloss, crystal pink",
    "jelly, translucent, gems",
    "Translucent jelly layers finished with crystal placements.",
    "Archived after spring campaign ended, still useful for references.",
  ],
  [
    "ND-3006",
    "Espresso Marble Lines",
    "Marble",
    "Autumn Preview",
    "Draft",
    "310,000 VND",
    "65 min",
    "Minh Nguyen",
    "New",
    "2026-06-02",
    "Espresso brown, oat milk, gold linework",
    "marble, neutral, editorial",
    "Neutral marble flow with thin metallic contour lines.",
    "Awaiting final pricing confirmation from operations.",
  ],
  [
    "ND-3007",
    "Pearl Bridal Veil",
    "Bridal",
    "Ceremony Suite",
    "Published",
    "480,000 VND",
    "100 min",
    "Alicia Tran",
    "Trending",
    "2026-05-26",
    "Pearl white, champagne shimmer, blush pink",
    "bridal, pearl, elegant",
    "Sheer bridal finish layered with pearls and shimmer gradients.",
    "Approved for wedding campaign and bundle promotions.",
  ],
  [
    "ND-3008",
    "Pop Art Citrus Grid",
    "Graphic",
    "Studio Lab",
    "Review",
    "360,000 VND",
    "80 min",
    "Quang Le",
    "Rising",
    "2026-06-03",
    "Citrus yellow, cobalt, crisp white",
    "graphic, editorial, bold",
    "Bold pop-art geometry with citrus tones and comic-style outlines.",
    "Waiting for admin review on campaign fit and target audience.",
  ],
];

export const NAIL_DESIGN_ROWS = NAIL_DESIGN_ROW_DEFINITIONS.map((definition) =>
  createMockNailDesign(...definition),
);

export const NAIL_DESIGN_STATUS_FILTERS = [
  "All",
  "Published",
  "Draft",
  "Review",
  "Archived",
];

export const NAIL_DESIGN_STATUS_STYLES = {
  Published: "bg-[#edfdf4] text-[#16975f]",
  Draft: "bg-[#fff7e7] text-[#cc8a16]",
  Review: "bg-[#eef4ff] text-[#3f68c9]",
  Archived: "bg-[#fff0f5] text-[#d14c84]",
};

export const NAIL_DESIGN_CATEGORY_OPTIONS = [
  "Chrome",
  "Minimal",
  "Aura",
  "Cat Eye",
  "Jelly",
  "Marble",
  "Bridal",
  "Graphic",
];

export const NAIL_DESIGN_COLLECTION_OPTIONS = [
  "Summer 2026",
  "Everyday Edit",
  "Night Luxe",
  "Glass Candy",
  "Autumn Preview",
  "Ceremony Suite",
  "Studio Lab",
];

export const NAIL_DESIGN_POPULARITY_OPTIONS = [
  "New",
  "Stable",
  "Rising",
  "Trending",
  "Cooling",
];

export const createEmptyNailDesign = () => ({
  id: "ND-NEW",
  name: "",
  category: NAIL_DESIGN_CATEGORY_OPTIONS[0],
  collection: NAIL_DESIGN_COLLECTION_OPTIONS[0],
  status: "Draft",
  price: "",
  duration: "60 min",
  artist: "",
  popularity: "New",
  updatedAt: "2026-06-05",
  palette: "",
  tags: "",
  description: "",
  notes: "",
});

export const getMockNailDesignById = (designId) =>
  NAIL_DESIGN_ROWS.find((design) => design.id === designId) ?? null;
