export const NAIL_DESIGN_SUMMARY = [
  {
    label: "Total designs",
    value: "8",
    description: "mock catalog entries available for admin review",
  },
  {
    label: "Featured",
    value: "3",
    description: "designs currently highlighted on promotional surfaces",
  },
  {
    label: "Draft concepts",
    value: "2",
    description: "designs still waiting for final merchandising approval",
  },
];

const createMockNailDesign = (
  id,
  name,
  category,
  collection,
  status,
  price,
  duration,
  artist,
  popularity,
  updatedAt,
  palette,
  tags,
  description,
  notes,
) => ({
  id,
  name,
  category,
  collection,
  status,
  price,
  duration,
  artist,
  popularity,
  updatedAt,
  palette,
  tags,
  description,
  notes,
});

const NAIL_DESIGN_ROW_DEFINITIONS = [
  [
    "ND-3001",
    "Rose Chrome Bloom",
    "Chrome",
    "Summer 2026",
    "Published",
    "420,000 VND",
    "90 min",
    "Ariana Vo",
    "Trending",
    "2026-05-30",
    "Rose gold, pearl white, mirror silver",
    "chrome, floral, bridal",
    "High-shine chrome base with sculpted rose petals and pearl accents.",
    "Pinned for homepage campaign and premium upsell bundle.",
  ],
  [
    "ND-3002",
    "Matcha Minimal Tips",
    "Minimal",
    "Everyday Edit",
    "Published",
    "260,000 VND",
    "55 min",
    "Bao Tran",
    "Stable",
    "2026-05-28",
    "Matcha green, nude beige, milky white",
    "minimal, short nails, office",
    "Clean diagonal French tips with soft green accents for daily wear.",
    "Performs well with office-worker audience in District 1.",
  ],
  [
    "ND-3003",
    "Sunset Aura Glaze",
    "Aura",
    "Summer 2026",
    "Draft",
    "390,000 VND",
    "75 min",
    "Linh Pham",
    "Rising",
    "2026-06-01",
    "Apricot, coral pink, soft amber",
    "aura, gradient, glossy",
    "Soft airbrushed aura blend with syrup gloss finish.",
    "Needs final photo retouch and naming approval before publishing.",
  ],
  [
    "ND-3004",
    "Velvet Midnight Cat Eye",
    "Cat Eye",
    "Night Luxe",
    "Published",
    "450,000 VND",
    "95 min",
    "Hanh Vo",
    "Trending",
    "2026-05-24",
    "Midnight blue, graphite, silver flare",
    "cat eye, magnetic, glam",
    "Magnetic cat-eye reflection with deep navy base and foil sparkle.",
    "Strong repeat-booking rate from evening event customers.",
  ],
  [
    "ND-3005",
    "Peach Jelly Crystals",
    "Jelly",
    "Glass Candy",
    "Archived",
    "340,000 VND",
    "70 min",
    "Thao Bui",
    "Cooling",
    "2026-04-19",
    "Peach jelly, clear gloss, crystal pink",
    "jelly, translucent, gems",
    "Translucent jelly layers finished with crystal placements.",
    "Archived after spring campaign ended, still useful for references.",
  ],
  [
    "ND-3006",
    "Espresso Marble Lines",
    "Marble",
    "Autumn Preview",
    "Draft",
    "310,000 VND",
    "65 min",
    "Minh Nguyen",
    "New",
    "2026-06-02",
    "Espresso brown, oat milk, gold linework",
    "marble, neutral, editorial",
    "Neutral marble flow with thin metallic contour lines.",
    "Awaiting final pricing confirmation from operations.",
  ],
  [
    "ND-3007",
    "Pearl Bridal Veil",
    "Bridal",
    "Ceremony Suite",
    "Published",
    "480,000 VND",
    "100 min",
    "Alicia Tran",
    "Trending",
    "2026-05-26",
    "Pearl white, champagne shimmer, blush pink",
    "bridal, pearl, elegant",
    "Sheer bridal finish layered with pearls and shimmer gradients.",
    "Approved for wedding campaign and bundle promotions.",
  ],
  [
    "ND-3008",
    "Pop Art Citrus Grid",
    "Graphic",
    "Studio Lab",
    "Review",
    "360,000 VND",
    "80 min",
    "Quang Le",
    "Rising",
    "2026-06-03",
    "Citrus yellow, cobalt, crisp white",
    "graphic, editorial, bold",
    "Bold pop-art geometry with citrus tones and comic-style outlines.",
    "Waiting for admin review on campaign fit and target audience.",
  ],
];

export const NAIL_DESIGN_ROWS = NAIL_DESIGN_ROW_DEFINITIONS.map((definition) =>
  createMockNailDesign(...definition),
);

export const NAIL_DESIGN_STATUS_FILTERS = [
  "All",
  "Published",
  "Draft",
  "Review",
  "Archived",
];

export const NAIL_DESIGN_STATUS_STYLES = {
  Published: "bg-[#edfdf4] text-[#16975f]",
  Draft: "bg-[#fff7e7] text-[#cc8a16]",
  Review: "bg-[#eef4ff] text-[#3f68c9]",
  Archived: "bg-[#fff0f5] text-[#d14c84]",
};

export const NAIL_DESIGN_CATEGORY_OPTIONS = [
  "Chrome",
  "Minimal",
  "Aura",
  "Cat Eye",
  "Jelly",
  "Marble",
  "Bridal",
  "Graphic",
];

export const NAIL_DESIGN_COLLECTION_OPTIONS = [
  "Summer 2026",
  "Everyday Edit",
  "Night Luxe",
  "Glass Candy",
  "Autumn Preview",
  "Ceremony Suite",
  "Studio Lab",
];

export const NAIL_DESIGN_POPULARITY_OPTIONS = [
  "New",
  "Stable",
  "Rising",
  "Trending",
  "Cooling",
];

export const createEmptyNailDesign = () => ({
  id: "ND-NEW",
  name: "",
  category: NAIL_DESIGN_CATEGORY_OPTIONS[0],
  collection: NAIL_DESIGN_COLLECTION_OPTIONS[0],
  status: "Draft",
  price: "",
  duration: "60 min",
  artist: "",
  popularity: "New",
  updatedAt: "2026-06-05",
  palette: "",
  tags: "",
  description: "",
  notes: "",
});

export const getMockNailDesignById = (designId) =>
  NAIL_DESIGN_ROWS.find((design) => design.id === designId) ?? null;

const DEFAULT_DESIGN_DETAIL = {
  breadcrumbsLabel: "Chrome Pearl Elegance",
  heroTitle: "Chrome Pearl Elegance",
  heroSubtitle:
    "A sophisticated chrome nail design featuring lustrous pearl accents and delicate gold line detailing.",
  designStatus: "Active",
  tryOnReady: true,
  complexity: "Advanced",
  estimatedDuration: "90 minutes",
  nailShape: "Almond",
  nailLength: "Medium",
  suggestedPrice: "₫680,000",
  popularityScore: "8.8/10",
  bookingRate: "74%",
  customerRating: "4.6★",
  customerProfile: {
    "Skin Tone": ["Fair", "Light Medium", "Medium"],
    "Skin Undertone": ["Cool", "Neutral"],
    Occasion: ["Wedding", "Party", "Photoshoot"],
    "Age Group": ["20s", "30s"],
    Style: ["Elegant", "Feminine", "Luxury"],
    Audience: ["Female", "Unisex"],
    Vibe: ["Soft but eye-catching"],
    "Hand Shape": ["Slim Fingers", "Long Fingers"],
  },
  designComponents: [
    ["Nail Length", "Medium"],
    ["Nail Shape", "Almond"],
    ["Main Color", "Pearl Chrome"],
    ["Surface / Finish", "Glossy"],
    ["Decoration", "Pearl + Gold Line"],
    ["Complexity", "Advanced"],
    ["Texture", "Chrome"],
    ["Pattern", "Minimal Pearl"],
  ],
  variants: [
    {
      name: "Minimal Pearl Variant",
      description: "Changed textured pearl density, no gold charm",
      materialDelta: "+₫30,000 material",
      priceDelta: "+₫50,000 price",
      level: "Intermediate",
      duration: "75 min",
    },
    {
      name: "Luxury Stone Variant",
      description: "Changed Swarovski crystal stones added",
      materialDelta: "+₫85,000 material",
      priceDelta: "+₫200,000 price",
      level: "Expert",
      duration: "110 min",
    },
    {
      name: "Bridal Pearl Variant",
      description: "Changed full pearl coverage + lace pattern",
      materialDelta: "+₫70,000 material",
      priceDelta: "+₫150,000 price",
      level: "Expert",
      duration: "120 min",
    },
    {
      name: "Gold Charm Variant",
      description: "Changed gold charm pendants on ring finger",
      materialDelta: "+₫45,000 material",
      priceDelta: "+₫90,000 price",
      level: "Advanced",
      duration: "95 min",
    },
  ],
  pricing: {
    materialCosts: [
      ["Gel Polish Cost", "₫45,000"],
      ["Chrome Powder Cost", "₫38,000"],
      ["Pearl Decoration Cost", "₫52,000"],
      ["Gold Line Cost", "₫18,000"],
      ["Tool Usage Cost", "₫12,000"],
    ],
    servicePricing: [
      ["Base Service Price", "₫280,000"],
      ["Decoration Fee", "₫80,000"],
      ["Complexity Fee", "₫60,000"],
      ["Staff Labor Fee", "₫120,000"],
      ["Variant Extra Fee", "₫0"],
    ],
    summary: [
      ["Total Material Cost", "₫165,000"],
      ["Total Service Price", "₫540,000"],
      ["Overhead & Tax (10%)", "₫54,000"],
      ["Suggested Selling Price", "₫680,000"],
      ["Estimated Profit", "₫461,000"],
      ["Profit Margin", "67.8%"],
    ],
    comparison: [
      ["Market Average", "₫620,000"],
      ["Our Price", "₫680,000"],
      ["Premium vs Market", "+9.7%"],
    ],
  },
  workflow: [
    ["Preparation", "5 min", ["Sanitizer", "Towel", "Tray"], "Easy"],
    ["Cleaning & Cuticle Care", "10 min", ["Cuticle Remover", "Pusher", "Nipper"], "Moderate"],
    ["Nail Shaping", "8 min", ["File", "Buffer", "Almond Form Guide"], "Moderate"],
    ["Base Coat Application", "5 min", ["Bonding Agent", "Base Gel"], "Easy"],
    ["Color Application", "13 min", ["Pearl Chrome Gel Polish (2 coats)"], "Advanced"],
    ["Chrome & Decoration", "20 min", ["Chrome Powder", "Pearl Beads", "Gold Liner"], "Expert"],
    ["Top Coat Sealing", "5 min", ["No-Wipe Top Coat", "Gel Sealer"], "Moderate"],
    ["UV/LED Drying", "15 min", ["LED Lamp 48W", "UV Lamp"], "Easy"],
    ["Final Review & Finishing", "10 min", ["Cuticle Oil", "Brush Cleaner"], "Easy"],
  ],
  skills: [
    ["Precision", "Accuracy & Detail", 4, "4★ Advanced"],
    ["Color", "Color Matching", 5, "5★ Expert"],
    ["Design", "Artistry", 5, "5★ Expert"],
    ["Form", "Nail Shape & Form", 3, "3★ Intermediate"],
    ["Material", "Material Handling", 4, "4★ Advanced"],
    ["Speed", "Job Speed", 3, "3★ Intermediate"],
  ],
  staffMatch: [
    ["Linh Nguyen", "94% match"],
    ["Mai Tran", "94% match"],
    ["Hoa Pham", "89% match"],
  ],
  eligibleArtists: "8",
  expertLevel: "3",
  advancedLevel: "5",
};

const DESIGN_DETAIL_OVERRIDES = {
  "ND-3001": {
    breadcrumbsLabel: "Chrome Pearl Elegance",
    heroTitle: "Chrome Pearl Elegance",
    heroSubtitle:
      "A sophisticated chrome nail design featuring lustrous pearl accents and delicate gold line detailing. Crafted for clients who desire an elevated, feminine aesthetic.",
  },
  "ND-3002": {
    breadcrumbsLabel: "Matcha Minimal Tips",
    heroTitle: "Matcha Minimal Tips",
    designStatus: "Active",
    complexity: "Intermediate",
    suggestedPrice: "₫420,000",
  },
  "ND-3004": {
    breadcrumbsLabel: "Velvet Midnight Cat Eye",
    heroTitle: "Velvet Midnight Cat Eye",
    complexity: "Expert",
    suggestedPrice: "₫720,000",
  },
};

export const getMockNailDesignDetailById = (designId) => {
  const base = getMockNailDesignById(designId);

  if (!base) {
    return null;
  }

  return {
    ...base,
    ...DEFAULT_DESIGN_DETAIL,
    ...(DESIGN_DETAIL_OVERRIDES[designId] ?? {}),
  };
};
