import { ROUTES } from "./routes";
import { ROLES } from "./roles";

export const MENU_CONFIG = {

  //staff
  [ROLES.staff]: [
    {
      key: "staff-dashboard",
      label: "Dashboard",
      to: ROUTES.staffDashboard,
      icon: "dashboard",
      section: "Main",
    },
    {
      key: "staff-bookings",
      label: "Bookings",
      to: ROUTES.staffBookings,
      icon: "calendar",
      section: "Main",
      badge: "8",
    },
    {
      key: "staff-tasks",
      label: "Tasks",
      to: ROUTES.staffTasks,
      icon: "tasks",
      section: "Main",
    },
    {
      key: "staff-customer-nails",
      label: "Custom Nails Reviews",
      to: ROUTES.staffCustomerNails,
      icon: "palette",
      section: "Main",
    },
    // {
    //   key: "staff-waitting",
    //   label: "Waitlist Alerts",
    //   to: ROUTES.staffWaitting,
    //   icon: "support",
    //   section: "Main",
    //   badge: "4",
    // },
    {
      key: "staff-schedule",
      label: "Schedule",
      to: ROUTES.staffSchedules,
      icon: "calendar",
      section: "Main",
    },
    {
      key: "staff-breaks",
      label: "Breaks",
      to: ROUTES.staffBreaks,
      icon: "clock",
      section: "Main",
    },
    // {
    //   key: "staff-customers",
    //   label: "Customers",
    //   icon: "users",
    //   section: "Support",
    //   disabled: true,
    // },
    {
      key: "staff-profile",
      label: "Profile",
      to: ROUTES.staffProfile,
      icon: "settings",
      section: "Support",
    },
  ],

  //receptionist
  [ROLES.receptionist]: [
    {
      key: "receptionist-dashboard",
      label: "Dashboard",
      to: ROUTES.receptionistDashboard,
      icon: "dashboard",
      section: "Main",
    },
    {
      key: "receptionist-bookings",
      label: "Bookings",
      to: ROUTES.receptionistBookings,
      icon: "calendar",
      section: "Main",
      badge: "24",
    },
    {
      key: "receptionist-customers",
      label: "Customers",
      to: ROUTES.receptionistCustomers,
      icon: "users",
      section: "Main",
    },
    {
      key: "receptionist-breaks",
      label: "Breaks",
      to: ROUTES.receptionistBreaks,
      icon: "clock",
      section: "Main",
    },
    // {
    //   key: "receptionist-waitlist",
    //   label: "Salon Waitlist",
    //   to: ROUTES.receptionistWaitlist,
    //   icon: "support",
    //   section: "Main",
    // },
    {
      key: "receptionist-chairs",
      label: "Chairs",
      to: ROUTES.receptionistChairs,
      icon: "armchair",
      section: "Main",
    },
    // {
    //   key: "receptionist-reviews",
    //   label: "Reviews",
    //   icon: "reviews",
    //   section: "Analytics",
    //   disabled: true,
    // },
    // {
    //   key: "receptionist-complaints",
    //   label: "Complaints",
    //   icon: "support",
    //   section: "Support",
    //   badge: "3",
    //   disabled: true,
    // },
    {
      key: "receptionist-profile",
      label: "Profile",
      to: ROUTES.receptionistProfile,
      icon: "settings",
      section: "Support",
    },
  ],
  //manager
  [ROLES.manager]: [
    {
      key: "manager-dashboard",
      label: "Dashboard",
      to: ROUTES.managerDashboard,
      icon: "dashboard",
      section: "Main",
    },
    {
      key: "manager-bookings",
      label: "Bookings",
      to: ROUTES.managerBookings,
      icon: "calendar",
      section: "Main",
      badge: "16",
    },
    // {
    //   key: "manager-waitlist",
    //   label: "Salon Waitlist",
    //   to: ROUTES.managerWaitlist,
    //   icon: "support",
    //   section: "Main",
    // },
    // {
    //   key: "manager-queue",
    //   label: "Walk-In Queue",
    //   to: ROUTES.managerQueue,
    //   icon: "users",
    //   section: "Main",
    // },
    {
      key: "manager-chairs",
      label: "Chairs",
      to: ROUTES.managerChairs,
      icon: "armchair",
    },
    {
      key: "manager-salon",
      label: "Salon Management",
      to: ROUTES.managerSalon,
      icon: "building",
    },
    {
      key: "manager-reschedule",
      label: "Reschedule",
      to: ROUTES.managerReschedule,
      icon: "clock",
      section: "Main",
    },
    // {
    //   key: "manager-waitlist",
    //   label: "Salon Waitlist",
    //   to: ROUTES.managerWaitlist,
    //   icon: "support",
    //   section: "Main",
    // },
    // {
    //   key: "manager-queue",
    //   label: "Walk-In Queue",
    //   to: ROUTES.managerQueue,
    //   icon: "users",
    //   section: "Main",
    // },
    {
      key: "manager-customer-nails",
      label: "Customer Nails",
      to: ROUTES.managerCustomerNails,
      icon: "palette",
      section: "Main",
    },
    {
      key: "manager-schedules",
      label: "Schedules",
      to: ROUTES.managerSchedules,
      icon: "calendar",
      section: "Main",
    },
    {
      key: "manager-staff",
      label: "Staff Artists",
      to: ROUTES.managerStaffArtists,
      icon: "users",
      section: "Main",
    },
    {
      key: "manager-breaks",
      label: "Artist Breaks",
      to: ROUTES.managerBreaks,
      icon: "clock",
      section: "Main",
    },
    {
      key: "manager-transactions",
      label: "Transactions",
      to: ROUTES.managerTransactions,
      icon: "wallet",
      section: "Main",
    },
    // {
    //   key: "manager-customers",
    //   label: "Customers",
    //   icon: "users",
    //   section: "Main",
    //   disabled: true,
    // },
    // {
    //   key: "manager-reports",
    //   label: "Analytics",
    //   icon: "analytics",
    //   section: "Analytics",
    //   disabled: true,
    // },
    {
      key: "manager-reviews",
      label: "Reviews",
      to: ROUTES.managerBookingRatings,
      icon: "reviews",
      section: "Analytics",
    },
    {
      key: "manager-profile",
      label: "Profile",
      to: ROUTES.managerProfile,
      icon: "settings",
      section: "Support",
    },
  ],

  //admin
  [ROLES.admin]: [
    {
      key: "admin-dashboard",
      label: "Dashboard",
      to: ROUTES.adminDashboard,
      icon: "dashboard",
      section: "Main",
    },
    {
      key: "admin-bookings",
      label: "Bookings",
      to: ROUTES.adminBookings,
      icon: "calendar",
      section: "Main",
      badge: "24",
    },
    {
      key: "admin-transactions",
      label: "Transactions",
      to: ROUTES.adminTransactions,
      icon: "wallet",
      section: "Main",
    },
    {
      key: "admin-salons",
      label: "Salons",
      to: ROUTES.adminSalons,
      icon: "store",
      section: "Main",
    },
    {
      key: "admin-chairs",
      label: "Chairs",
      to: ROUTES.adminChairs,
      icon: "armchair", // Ensure you have this icon mapped if it's dynamic
      section: "Main",
    },
    {
      key: "admin-staff",
      label: "Staff",
      to: ROUTES.adminStaff,
      icon: "users",
      section: "Main",
    },
    {
      key: "admin-users",
      label: "Users",
      to: ROUTES.adminUsers,
      icon: "users",
      section: "Main",
    },
    {
      key: "admin-loyalty-tiers",
      label: "Loyalty Tiers",
      to: ROUTES.adminLoyaltyTiers,
      icon: "award",
      section: "Main",
    },
    {
      key: "admin-loyalty-transactions",
      label: "Loyalty Transactions",
      to: ROUTES.adminLoyaltyTransactions,
      icon: "award",
      section: "Main",
    },
    {
      key: "admin-quiz",
      label: "Quiz",
      to: ROUTES.adminQuiz,
      icon: "quiz",
      section: "Main",
    },
    {
      key: "admin-nail-designs",
      label: "Nail Designs",
      to: ROUTES.adminNailDesigns,
      icon: "palette",
      section: "Main",
    },
    {
      key: "admin-service-pricing",
      label: "Services",
      to: ROUTES.adminServicePricing,
      icon: "scissors",
      section: "Main",
    },
    {
      key: "admin-nail-shapes",
      label: "Nail Shapes",
      to: ROUTES.adminNailShapes,
      icon: "shapes",
      section: "Main",
    },
    {
      key: "admin-nail-surfaces",
      label: "Nail Surfaces",
      to: ROUTES.adminNailSurfaces,
      icon: "layers",
      section: "Main",
    },
    {
      key: "admin-components",
      label: "Components",
      to: ROUTES.adminComponents,
      icon: "puzzle",
      section: "Main",
    },
    {
      key: "admin-procedures",
      label: "Procedures",
      to: ROUTES.adminProcedures,
      icon: "clipboard-list",
      section: "Main",
    },
    {
      key: "admin-category-types",
      label: "Category Types",
      to: ROUTES.adminCategoryTypes,
      icon: "tags",
      section: "Main",
    },
    {
      key: "admin-categories",
      label: "Categories",
      to: ROUTES.adminCategories,
      icon: "folder-tree",
      section: "Main",
    },
    {
      key: "admin-skill-types",
      label: "Skill Types",
      to: ROUTES.adminSkillTypes,
      icon: "wand2",
      section: "Main",
    },

    {
      key: "admin-promotions",
      label: "Promotions",
      to: ROUTES.adminPromotions,
      icon: "gift",
      section: "Main",
    },

    // {
    //   key: "admin-analytics",
    //   label: "Analytics",
    //   icon: "analytics",
    //   section: "Analytics",
    //   disabled: true,
    // },
    {
      key: "admin-reviews",
      label: "Reviews",
      to: ROUTES.adminBookingRatings,
      icon: "reviews",
      section: "Analytics",
    },
    // {
    //   key: "admin-complaints",
    //   label: "Complaints",
    //   icon: "support",
    //   section: "Support",
    //   badge: "7",
    //   disabled: true,
    // },
    {
      key: "admin-profile",
      label: "Profile",
      to: ROUTES.adminProfile,
      icon: "settings",
      section: "Support",
    },
  ],
};

export function getMenuConfig(role) {
  const menus = MENU_CONFIG[role] ?? [];

  return menus.map((item) => {
    const menuItem = { ...item };
    delete menuItem.badge;
    return menuItem;
  });
}
