import { ROUTES } from "./routes";
import { ROLES } from "./roles";

export const MENU_CONFIG = {
  [ROLES.staff]: [
    {
      key: "staff-dashboard",
      label: "Dashboard",
      to: ROUTES.staffDashboard,
      icon: "dashboard",
      section: "Main",
    },
    {
      key: "staff-bookings",
      label: "Bookings",
      to: ROUTES.staffBookings,
      icon: "calendar",
      section: "Main",
      badge: "8",
    },
    {
      key: "staff-schedule",
      label: "Schedule",
      icon: "calendar",
      section: "Main",
      disabled: true,
    },
    {
      key: "staff-customers",
      label: "Customers",
      icon: "users",
      section: "Support",
      disabled: true,
    },
    {
      key: "staff-settings",
      label: "Settings",
      icon: "settings",
      section: "Support",
      disabled: true,
    },
  ],
  [ROLES.receptionist]: [
    {
      key: "receptionist-dashboard",
      label: "Dashboard",
      to: ROUTES.staffDashboard,
      icon: "dashboard",
      section: "Main",
    },
    {
      key: "receptionist-bookings",
      label: "Bookings",
      to: ROUTES.receptionistBookings,
      icon: "calendar",
      section: "Main",
      badge: "24",
    },
    {
      key: "receptionist-customers",
      label: "Customers",
      icon: "users",
      section: "Main",
      disabled: true,
    },
    {
      key: "receptionist-reviews",
      label: "Reviews",
      icon: "reviews",
      section: "Analytics",
      disabled: true,
    },
    {
      key: "receptionist-complaints",
      label: "Complaints",
      icon: "support",
      section: "Support",
      badge: "3",
      disabled: true,
    },
    {
      key: "receptionist-settings",
      label: "Settings",
      icon: "settings",
      section: "Support",
      disabled: true,
    },
  ],
  [ROLES.manager]: [
    {
      key: "manager-dashboard",
      label: "Dashboard",
      to: ROUTES.managerDashboard,
      icon: "dashboard",
      section: "Main",
    },
    {
      key: "manager-bookings",
      label: "Bookings",
      to: ROUTES.managerBookings,
      icon: "calendar",
      section: "Main",
      badge: "16",
    },
    {
      key: "manager-schedules",
      label: "Schedules",
      icon: "calendar",
      section: "Main",
      disabled: true,
    },
    {
      key: "manager-staff",
      label: "Staff Artists",
      icon: "users",
      section: "Main",
      disabled: true,
    },
    {
      key: "manager-customers",
      label: "Customers",
      icon: "users",
      section: "Main",
      disabled: true,
    },
    {
      key: "manager-reports",
      label: "Analytics",
      icon: "analytics",
      section: "Analytics",
      disabled: true,
    },
    {
      key: "manager-reviews",
      label: "Reviews",
      icon: "reviews",
      section: "Analytics",
      disabled: true,
    },
    {
      key: "manager-settings",
      label: "Settings",
      icon: "settings",
      section: "Support",
      disabled: true,
    },
  ],
  [ROLES.admin]: [
    {
      key: "admin-dashboard",
      label: "Dashboard",
      to: ROUTES.adminDashboard,
      icon: "dashboard",
      section: "Main",
    },
    {
      key: "admin-bookings",
      label: "Bookings",
      to: ROUTES.adminBookings,
      icon: "calendar",
      section: "Main",
      badge: "24",
    },
    {
      key: "admin-salons",
      label: "Salons",
      icon: "store",
      section: "Main",
      disabled: true,
    },
    {
      key: "admin-users",
      label: "User Management",
      to: ROUTES.adminUsers,
      icon: "users",
      section: "Main",
    },
    {
      key: "admin-analytics",
      label: "Analytics",
      icon: "analytics",
      section: "Analytics",
      disabled: true,
    },
    {
      key: "admin-reviews",
      label: "Reviews",
      icon: "reviews",
      section: "Analytics",
      disabled: true,
    },
    {
      key: "admin-complaints",
      label: "Complaints",
      icon: "support",
      section: "Support",
      badge: "7",
      disabled: true,
    },
    {
      key: "admin-settings",
      label: "Settings",
      icon: "settings",
      section: "Support",
      disabled: true,
    },
  ],
};
